version: 1.0.{build}

image: Visual Studio 2015

clone_folder: c:\projects\tt

clone_depth: 1

before_build:
  - set CMAKE_PREFIX_PATH=C:\Qt\5.13.2\msvc2015_64\
  - cmake -G "Visual Studio 14 2015 Win64" -DTT_BUILD_EXAMPLES=TRUE

build:
  parallel: true
  project: TabToolbar.sln
  verbosity: normal